### ISSUE TITLE
issues in python 3.8

### ISSUE THREAD

**Issue by johnfelipe** [VermaSanjayrk/Face_Emotion_Recognition#1]
root@felipe:~/Face_Emotion_Recognition# streamlit run streamlit_app.py
	Traceback (most recent call last):
	  File "/usr/local/lib/python3.8/dist-packages/pandas/compat/_optional.py", line 138, in import_optional_dependency
		module = importlib.import_module(name)
	  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
		return _bootstrap._gcd_import(name[level:], package, level)
	  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
	  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
	  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
	  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
	  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
	  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
	  File "/usr/lib/python3/dist-packages/jinja2/__init__.py", line 33, in <module>
		from jinja2.environment import Environment, Template
	  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 15, in <module>
		from jinja2 import nodes
	  File "/usr/lib/python3/dist-packages/jinja2/nodes.py", line 23, in <module>
		from jinja2.utils import Markup
	  File "/usr/lib/python3/dist-packages/jinja2/utils.py", line 656, in <module>
		from markupsafe import Markup, escape, soft_unicode
	ImportError: cannot import name 'soft_unicode' from 'markupsafe' (/usr/local/lib/python3.8/dist-packages/markupsafe/__init__.py)

	During handling of the above exception, another exception occurred:

	Traceback (most recent call last):
	  File "/usr/local/bin/streamlit", line 5, in <module>
		from streamlit.cli import main
	  File "/usr/local/lib/python3.8/dist-packages/streamlit/__init__.py", line 70, in <module>
		from streamlit.delta_generator import DeltaGenerator as _DeltaGenerator
	  File "/usr/local/lib/python3.8/dist-packages/streamlit/delta_generator.py", line 72, in <module>
		from streamlit.elements.arrow import ArrowMixin
	  File "/usr/local/lib/python3.8/dist-packages/streamlit/elements/arrow.py", line 20, in <module>
		from pandas.io.formats.style import Styler
	  File "/usr/local/lib/python3.8/dist-packages/pandas/io/formats/style.py", line 52, in <module>
		jinja2 = import_optional_dependency("jinja2", extra="DataFrame.style requires jinja2.")
	  File "/usr/local/lib/python3.8/dist-packages/pandas/compat/_optional.py", line 141, in import_optional_dependency
		raise ImportError(msg)
	ImportError: Missing optional dependency 'Jinja2'. DataFrame.style requires jinja2. Use pip or conda to install Jinja2.

**Comment by johnfelipe** [comment]
solved

```
pip install flask
pip install -U click==8

```
